### ISSUE TITLE
Wiggle Knobs Randomization doesn't work in Cookies

### ISSUE THREAD

**Issue by FMTolstoevsky** [freddyz/computerscare-vcv-modules#20]
Hi, Adam, very nice to see finally your collection, thanks a lot!
Unfortunately my old favorite, Cookies, doesn't behave as I hoped for now.
Main problem is written in the title + it's a pity that I can't use my old 062 presets, which I made.. (in fact I can but it doesn't reproduce text fields at least).

**Comment by freddyz** [comment]
I'm pretty sure I just forgot to implement the "wiggle knobs" function.  I'm surprised that the text fields aren't loading properly... I will look into it.  Thank you for the bug report!

**Comment by FMTolstoevsky** [comment]
Thanks for your quick response, hope that you could fix at least "wiggle knobs" :)
Meanwhile I'll try to examine your new modules!

**Comment by freddyz** [comment]
I think I fixed both the problems.  Could you confirm that your patches are loading properly with v1.0.1: https://github.com/freddyz/computerscare-vcv-modules/releases/tag/v1.0.1 . I can create a windows build too if you need it

**Comment by FMTolstoevsky** [comment]
Yes, please, I am using Windows, so I can't test your new build so far. Thanx in advance!

**Comment by freddyz** [comment]
I added a windows build to the 1.0.2 release.  Please test using this one: https://github.com/freddyz/computerscare-vcv-modules/releases/tag/v1.0.2

**Comment by FMTolstoevsky** [comment]
Got it, thx, will check now

**Comment by FMTolstoevsky** [comment]
Well, here are my first impressions: 1) in general, everything works OK, i.e. my old presets are readable & sound like they used to :) 2) but there's one tricky catch: as I understand, your new version of Cookies  has very thin volt-range of 0-1V (rather strange range IMHO, BTW), whereas Old version had 0-5V or may be even 0-10V range (still can't quite calculate it even with NYSTHI's Multivoltimetro :) AND all my old presets obviously were saved with that "wide range" + they  are loading up correctly, preserving those old volt-ranges. BUT each time I try to change any knobs manually all those "wide-voltages data" immediately are converted into new "thin ones" (0-1V). 
3) There is another funny catch (and I am still wondering if it was made on purpose by you or not) - 
if I use general "Randomize" option (from right-click menu) it changes all data in that new thin range, but if I use "Wiggle knobs" instead it modifies all data (knobs) again in wide-range (at least when I use those old presets of mine!). So, please, just clarify, if it's OK, or such "dual behaviour" was not planned by you.

**Comment by freddyz** [comment]
You're right - previously the range was 1-10V and now I realize that I have forgotten to configure the knobs the proper way for Rack v1.  Good catch - thanks!

**Comment by FMTolstoevsky** [comment]
Well-well...;) So, do you intend to make it again as before (0-10V) or...?

**Comment by freddyz** [comment]
Yes I will fix the knob ranges so that they are 0-10v.

**Comment by FMTolstoevsky** [comment]
Fine, that's the best way to do it.

**Comment by freddyz** [comment]
New release 1.0.3 with everybody's favorite voltage range for the knobs. https://github.com/freddyz/computerscare-vcv-modules/releases/tag/v1.0.3

**Comment by FMTolstoevsky** [comment]
Excellent, Adam, now I am happy at last! And special thanks for clear indications of volts for knobs.

**Comment by freddyz** [comment]
Fantastic!  Thanks a lot for pointing out the bugs.  The textfield loading issue was also a problem for 2 of my other modules.
